solr_assocs:
  url: "https://solr.monarchinitiative.org/solr/golr"
  timeout: 15
amigo_solr_assocs:
  url: "http://golr.berkeleybop.org"
  timeout: 15
solr_search:
  url: "https://solr.monarchinitiative.org/solr/search"
  timeout: 15
amigo_solr_search:
  url: "http://golr.berkeleybop.org"
  timeout: 15
sparql:
  url: "http://sparql.hegroup.org/sparql"
  timeout: 15
scigraph_ontology:
  url: "https://scigraph-ontology.monarchinitiative.org/scigraph/"
  timeout: 15
scigraph_data:
  url: "https://scigraph-data.monarchinitiative.org/scigraph/"
  timeout: 15
use_amigo_for:
  - function
ontologies:
  - id: go
    handle: go
    pre_load: false
  - id: hp
    handle: hp
    pre_load: false
#  - id: mp
#    handle: mp
#    pre_load: false
  - id: uberon
    handle: uberon
    pre_load: false
  - id: mondo
    handle: mondo
    pre_load: false
#  - id: monarch
#    handle: data/monarch.json
#    pre_load: false
