route_mapping:
  namespace:

    - name: bioentity
      description: Retrieval of domain entities plus associations
      routes:
        - route: /<id>
          resource: biolink.api.bio.endpoints.bioentity.GenericObject
        - route: /<type>/<id>
          resource: biolink.api.bio.endpoints.bioentity.GenericObjectByType
        - route: /<id>/associations
          resource: biolink.api.bio.endpoints.bioentity.GenericAssociations
        - route: /gene/<id>/homologs
          resource: biolink.api.bio.endpoints.bioentity.GeneHomologAssociations
        - route: /gene/<id>/function
          resource: biolink.api.bio.endpoints.bioentity.GeneFunctionAssociations
        - route: /gene/<id>/publications
          resource: biolink.api.bio.endpoints.bioentity.GenePublicationAssociations
        - route: /function/<id>/genes
          resource: biolink.api.bio.endpoints.bioentity.FunctionGeneAssociations
        - route: /function/<id>
          resource: biolink.api.bio.endpoints.bioentity.FunctionAssociations
        - route: /function/<id>/taxons
          resource: biolink.api.bio.endpoints.bioentity.FunctionTaxonAssociations
        - route: /function/<id>/publications
          resource: biolink.api.bio.endpoints.bioentity.FunctionPublicationAssociations
        - route: /publication/<id>/genes
          resource: biolink.api.bio.endpoints.bioentity.PublicationGeneAssociations

    - name: association
      description: Retrieve associations between entities or entity and descriptors
      routes:
        - route: /<id>
          resource: biolink.api.link.endpoints.find_associations.AssociationObject
        - route: /find/<subject_category>
          resource: biolink.api.link.endpoints.find_associations.AssociationBySubjectCategorySearch
        - route: /find/<subject_category>/<object_category>
          resource: biolink.api.link.endpoints.find_associations.AssociationBySubjectAndObjectCategorySearch
        - route: /from/<subject>
          resource: biolink.api.link.endpoints.associations_from.AssociationsFrom
        - route: /to/<object>
          resource: biolink.api.link.endpoints.associations_from.AssociationsTo
        - route: /between/<subject>/<object>
          resource: biolink.api.link.endpoints.associations_from.AssociationsBetween

    # - name: cam
    #   description: Operations on GO Causal Activity Models (GO-CAMs)
    #   routes:
    #     - route: /model
    #       resource: biolink.api.cam.endpoints.cam_endpoint.ModelCollection
    #     - route: /model/query
    #       resource: biolink.api.cam.endpoints.cam_endpoint.ModelQuery
    #     - route: /model/properties
    #       resource: biolink.api.cam.endpoints.cam_endpoint.ModelProperties
    #     - route: /model/contributors
    #       resource: biolink.api.cam.endpoints.cam_endpoint.ModelContributors
    #     - route: /instances
    #       resource: biolink.api.cam.endpoints.cam_endpoint.ModelInstances
    #     - route: /model/property_values
    #       resource: biolink.api.cam.endpoints.cam_endpoint.ModelPropertyValues
    #     - route: /model/<id>
    #       resource: biolink.api.cam.endpoints.cam_endpoint.ModelObject
    #     - route: /instance/<id>
    #       resource: biolink.api.cam.endpoints.cam_endpoint.InstanceObject
    #     - route: /activity
    #       resource: biolink.api.cam.endpoints.cam_endpoint.ActivityCollection
    #     - route: /physical_interaction
    #       resource: biolink.api.cam.endpoints.cam_endpoint.PhysicalInteraction

    - name: bioentityset
      description: Operations over sets of entities
      routes:
        - route: /descriptor/counts
          resource: biolink.api.entityset.endpoints.summary.EntitySetSummary
        - route: /associations
          resource: biolink.api.entityset.endpoints.summary.EntitySetAssociations
        - route: /graph
          resource: biolink.api.entityset.endpoints.summary.EntitySetGraphResource
        - route: /overrepresentation
          resource: biolink.api.entityset.endpoints.overrepresentation.OverRepresentation

    # - name: bioentityset/homologs
    #   description: Map gene IDs to their homologs
    #   routes:
    #     - route: /
    #       resource: biolink.api.entityset.endpoints.geneset_homologs.EntitySetHomologs

    - name: bioentityset/slimmer
      description: maps a set of entities to a slim      
      routes:
        - route: /function
          resource: biolink.api.entityset.endpoints.slimmer.EntitySetFunctionSlimmer

    # - name: evidence/graph
    #   description: Operations on evidence graphs
    #   routes:
    #     - route: /<id>
    #       resource: biolink.api.evidence.endpoints.graph.EvidenceGraphObject
    #     - route: /<id>/image
    #       resource: biolink.api.evidence.endpoints.graph.EvidenceGraphImage

    - name: graph
      description: Operations over data graphs
      routes:
        - route: /node/<id>
          resource: biolink.api.graph.endpoints.node.NodeResource
        - route: /edges/from/<id>
          resource: biolink.api.graph.endpoints.node.EdgeResource
          
    - name: identifier/prefixes
      description: identifier prefixes
      routes:
        - route: /
          resource: biolink.api.identifier.endpoints.prefixes.PrefixCollection
        - route: /expand/<id>
          resource: biolink.api.identifier.endpoints.prefixes.PrefixExpand
        - route: /contract/<path:uri>
          resource: biolink.api.identifier.endpoints.prefixes.PrefixContract

    # - name: mart
    #   description: Perform bulk operations
    #   routes:
    #     - route: /gene/<object_category>/<taxon>
    #       resource: biolink.api.mart.endpoints.mart.MartGeneAssociationsResource
    #     - route: /paralog/<taxon1>/<taxon2>
    #       resource: biolink.api.mart.endpoints.mart.MartParalogAssociationsResource
    #     - route: /ortholog/<taxon1>/<taxon2>
    #       resource: biolink.api.mart.endpoints.mart.MartOrthologAssociationsResource
          
    # - name: ontol
    #   description: extract a subgraph from an ontology
    #   routes:
    #     - route: /subgraph/<ontology>/<node>
    #       resource: biolink.api.ontol.endpoints.subgraph.ExtractOntologySubgraphResource
    #     - route: /information_content/<subject_category>/<object_category>/<subject_taxon>
    #       resource: biolink.api.ontol.endpoints.termstats.InformationContentResource

    - name: ontol/labeler
      description: Assign labels to IDs
      routes:
        - route: /
          resource: biolink.api.ontol.endpoints.labeler.OntolLabelerResource

    - name: ontology
      description: Operations on Ontology Terms and Subsets
      routes:
        - route: /term/<id>
          resource: biolink.api.ontol.endpoints.ontology_endpoint.OntologyTerm
        - route: /term/<id>/graph
          resource: biolink.api.ontol.endpoints.ontology_endpoint.OntologyTermGraph
        - route: /term/<id>/subgraph
          resource: biolink.api.ontol.endpoints.ontology_endpoint.OntologyTermSubgraph
        - route: /term/<id>/subsets
          resource: biolink.api.ontol.endpoints.ontology_endpoint.OntologyTermSubsets
        - route: /subset/<id>
          resource: biolink.api.ontol.endpoints.ontology_endpoint.OntologySubset
        - route: /ribbon/
          resource: biolink.api.ontol.endpoints.ontology_endpoint.OntologyRibbons
        - route: /shared/<subject>/<object>
          resource: biolink.api.ontol.endpoints.ontology_endpoint.OntologyTermsSharedAncestor

    # - name: owl/ontology
    #   description: OWL-level operations on an ontology
    #   routes:
    #     - route: /dlquery/<query>
    #       resource: biolink.api.owl.endpoints.ontology.DLQuery
    #     - route: /sparql/<query>
    #       resource: biolink.api.owl.endpoints.ontology.SparqlQuery

    # - name: pair/sim
    #   description: pairwise similarity between two entities
    #   routes:
    #     - route: /jaccard/<id1>/<id2>
    #       resource: biolink.api.pair.endpoints.pairsim.PairSimJaccardResource

    - name: search
      description: Search for entities
      routes:
        - route: /entity/<term>
          resource: biolink.api.search.endpoints.entitysearch.SearchEntities
        - route: /entity/autocomplete/<term>
          resource: biolink.api.search.endpoints.entitysearch.Autocomplete

    # Those routes are producing continuous WORKER TIMEOUT
    # - name: sim
    #   description: Perform semantic similarity, ranking, and classification
    #   routes:
    #       - route: /score
    #         resource: biolink.api.sim.endpoints.annotation_score.AnnotationScore
    #       - route: /search
    #         resource: biolink.api.sim.endpoints.semanticsim.SimSearch
    #       - route: /compare
    #         resource: biolink.api.sim.endpoints.semanticsim.SimCompare
